name: After merge main testing

on:
  pull_request:
    types:
      - closed

jobs:
  test_main_after_mergin:
      runs-on: ubuntu-latest
      steps:
        - name: Wait for Before Merge Workflow to Complete
          run: sleep 60s  # You can adjust the sleep duration as needed
  
        - name: Check if PR was merged
          run: |
            if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
              echo "Pull request was successfully merged, triggering Playwright tests on main branch."
              # Add any additional conditions you need here before triggering the tests.
              echo "::set-output name=run_tests::true"
            else
              echo "No PR was merged, no additional tests to run."
              echo "::set-output name=run_tests::false"
            fi
          id: check_merged
  
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '16'
  
        - name: Install dependencies
          run: npm install
            
        - name: Set up XVFB (virtual display)
          run: |
            sudo apt-get update
            sudo apt-get install xvfb xorg
            Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
            export DISPLAY=:99
        
            # Start the X server with the virtual display
            Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./Xorg.0.log -config /etc/X11/xorg.conf :99
        
        - name: Run Playwright tests in headed mode
          run: |
            if: steps.check_merged.outputs.run_tests == 'true'
            xvfb-run npx playwright test --headed
          
          