name: After merge main testing

on:
  pull_request:
    types:
      - closed

jobs:
  test_main_after_mergin:
      runs-on: windows-latest # Use a Windows runner
      steps:
        - name: Wait for Before Merge Workflow to Complete
          run: sleep 60s  # You can adjust the sleep duration as needed
  
        - name: Check if PR was merged
          run: |
            if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
              echo "Pull request was successfully merged, triggering Playwright tests on main branch."
              # Add any additional conditions you need here before triggering the tests.
              echo "::set-output name=run_tests::true"
            else
              echo "No PR was merged, no additional tests to run."
              echo "::set-output name=run_tests::false"
            fi
          id: check_merged
  
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '16'

        - name: Install dependencies
          run: npm install

        - name: Install Chrome with Chocolatey
          run: choco install googlechrome --yes
        - name: Add Chrome to PATH
          run: |
            echo "::add-path::C:\Program Files\Google\Chrome\Application"

        - name: Install Playwright browsers
          run: npx playwright install
        
        - name: Run Playwright tests
          if: ${{ steps.check_merged.outputs.run_tests == 'true' }}
          run: |
            npx playwright test --headed

          
          