name: Before merge main testing CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Clear Node Modules and Cache
        run: |
          rm -rf node_modules
          npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Check Jest Permissions
        run: ls -l node_modules/.bin/jest

      - name: Add node_modules/.bin to PATH
        run: export PATH="./node_modules/.bin:$PATH"
      
      - name: Add Executable Permissions to Jest
        run: chmod +x node_modules/.bin/jest

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Set up XVFB (virtual display)
        run: |
          sudo apt-get update
          sudo apt-get install xvfb xorg
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          export DISPLAY=:99
      
          # Start the X server with the virtual display
          Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./Xorg.0.log -config /etc/X11/xorg.conf :99
      
      - name: Run Playwright tests in headed mode
        run: |
          xvfb-run npx playwright test --headed

      - name: Debug Environment
        run: |
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "GitHub Actions Runner Info"
          echo "---------------------------------------------"
          npx playwright info
          echo "---------------------------------------------"