name: Before merge main testing CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest # Use a Windows runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

  test:
    runs-on: windows-latest # Use a Windows runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Clear Node Modules and Cache
        run: |
          rd /s /q node_modules
          npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run the tests
        run: |
          npx playwright test --headed
